import type {
  NarrativeAssertion,
  NarrativeChapter,
  NarrativeGap,
  NarrativeObjectBundle,
  NarrativeRelationship,
  NarrativeScene,
  StoryUnit,
} from "./narrativeObjectContract";

const authoredProvenance = {
  origin: "author",
  status: "authored",
  confidence: "high",
  authorConfirmed: true,
  source: "manual-fixture",
  note: "Manually authored contract example.",
} as const;

const inferredProvenance = {
  origin: "companion",
  status: "inferred",
  confidence: "medium",
  authorConfirmed: false,
  source: "companion-suggestion",
  note: "Candidate relationship or grouping inferred by advisory tooling.",
} as const;

const systemDerivedProvenance = {
  origin: "derived",
  status: "derived",
  confidence: "high",
  authorConfirmed: false,
  source: "scene-compatibility-layer",
  note: "Derived from scene-first compatibility scaffolding.",
} as const;

const authoredLifecycle = {
  state: "active",
  createdAt: "2026-06-05T00:00:00Z",
  updatedAt: "2026-06-05T00:00:00Z",
  archivedAt: null,
} as const;

const activeLineage = {
  originId: "nar_larry_boat",
  parentIds: [] as const,
  mergedFromIds: [] as const,
  splitFromId: null,
  promotedFromId: null,
  supersededById: null,
  childIds: [] as const,
  branchId: null,
} as const;

export const NARRATIVE_ASSERTION_FIXTURES: readonly NarrativeAssertion[] = [
  {
    id: "nar_larry_boat",
    kind: "narrative_assertion",
    text: "Larry got on a boat.",
    normalizedText: "Larry got on a boat.",
    sceneId: null,
    tags: ["larry", "boat", "travel"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: activeLineage,
  },
  {
    id: "nar_larry_fish",
    kind: "narrative_assertion",
    text: "Larry caught a fish.",
    normalizedText: "Larry caught a fish.",
    sceneId: null,
    tags: ["larry", "fish", "event"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_fish",
    },
  },
  {
    id: "nar_larry_dinner",
    kind: "narrative_assertion",
    text: "Larry had dinner with friends.",
    normalizedText: "Larry had dinner with friends.",
    sceneId: null,
    tags: ["larry", "dinner", "friends"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_dinner",
    },
  },
  {
    id: "nar_larry_poisoned",
    kind: "narrative_assertion",
    text: "Larry was poisoned.",
    normalizedText: "Larry was poisoned.",
    sceneId: null,
    tags: ["larry", "poison", "state"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_poisoned",
    },
  },
  {
    id: "nar_larry_died",
    kind: "narrative_assertion",
    text: "Larry died of poison.",
    normalizedText: "Larry died of poison.",
    sceneId: null,
    tags: ["larry", "death", "poison"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_died",
    },
  },
  {
    id: "nar_larry_survives",
    kind: "narrative_assertion",
    text: "Larry survives.",
    normalizedText: "Larry survives.",
    sceneId: null,
    tags: ["larry", "survival", "contradiction"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_survives",
    },
  },
  {
    id: "nar_larry_not_poisoned",
    kind: "narrative_assertion",
    text: "Larry was not poisoned.",
    normalizedText: "Larry was not poisoned.",
    sceneId: null,
    tags: ["larry", "poison", "negation"],
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      ...activeLineage,
      originId: "nar_larry_not_poisoned",
    },
  },
];

export const NARRATIVE_STORY_UNIT_FIXTURES: readonly StoryUnit[] = [
  {
    id: "su_larry_day",
    kind: "story_unit",
    title: "Larry's day at sea",
    assertionIds: ["nar_larry_boat", "nar_larry_fish", "nar_larry_dinner"],
    anchorAssertionIds: ["nar_larry_boat", "nar_larry_dinner"],
    order: 1,
    sceneCandidateId: null,
    sceneId: null,
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "su_larry_day",
      parentIds: ["nar_larry_boat", "nar_larry_fish", "nar_larry_dinner"],
      mergedFromIds: ["nar_larry_boat", "nar_larry_fish", "nar_larry_dinner"],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: ["su_larry_evening"],
      branchId: null,
    },
  },
  {
    id: "su_larry_evening",
    kind: "story_unit",
    title: "Larry's evening pivot",
    assertionIds: ["nar_larry_dinner", "nar_larry_poisoned", "nar_larry_died"],
    anchorAssertionIds: ["nar_larry_dinner", "nar_larry_died"],
    order: 2,
    sceneCandidateId: null,
    sceneId: null,
    provenance: inferredProvenance,
    lifecycle: {
      ...authoredLifecycle,
      state: "candidate",
    },
    lineage: {
      originId: "su_larry_evening",
      parentIds: ["su_larry_day"],
      mergedFromIds: [],
      splitFromId: "su_larry_day",
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: "branch_larry_evening",
    },
  },
];

export const NARRATIVE_GAP_FIXTURES: readonly NarrativeGap[] = [
  {
    id: "gap_larry_midday",
    kind: "narrative_gap",
    description: "The middle of Larry's day remains unresolved between the boat trip and dinner.",
    startAnchorIds: ["nar_larry_boat"],
    endAnchorIds: ["nar_larry_dinner"],
    relatedRelationshipIds: ["rel_larry_continues"],
    provenance: inferredProvenance,
    lifecycle: {
      ...authoredLifecycle,
      state: "candidate",
    },
    lineage: {
      originId: "gap_larry_midday",
      parentIds: ["nar_larry_boat", "nar_larry_dinner"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: null,
    },
  },
];

export const NARRATIVE_RELATIONSHIP_FIXTURES: readonly NarrativeRelationship[] = [
  {
    id: "rel_larry_continues",
    kind: "narrative_relationship",
    sourceId: "nar_larry_boat",
    targetId: "nar_larry_fish",
    relationshipType: "continues",
    category: "narrative",
    description: "Larry's boat trip continues into fishing.",
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "rel_larry_continues",
      parentIds: ["nar_larry_boat", "nar_larry_fish"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: null,
    },
  },
  {
    id: "rel_larry_poison_causes_death",
    kind: "narrative_relationship",
    sourceId: "nar_larry_poisoned",
    targetId: "nar_larry_died",
    relationshipType: "causes",
    category: "narrative",
    description: "Poisoning explains the death line.",
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "rel_larry_poison_causes_death",
      parentIds: ["nar_larry_poisoned", "nar_larry_died"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: null,
    },
  },
  {
    id: "rel_larry_contradiction",
    kind: "narrative_relationship",
    sourceId: "nar_larry_died",
    targetId: "nar_larry_survives",
    relationshipType: "contradicts",
    category: "narrative",
    description: "Larry dies and Larry survives cannot both be authoritative without branch handling.",
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "rel_larry_contradiction",
      parentIds: ["nar_larry_died", "nar_larry_survives"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: "branch_larry_contradiction",
    },
  },
  {
    id: "rel_larry_poison_negation",
    kind: "narrative_relationship",
    sourceId: "nar_larry_poisoned",
    targetId: "nar_larry_not_poisoned",
    relationshipType: "contradicts",
    category: "narrative",
    description: "Poisoned and not poisoned remain competing assertions.",
    provenance: authoredProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "rel_larry_poison_negation",
      parentIds: ["nar_larry_poisoned", "nar_larry_not_poisoned"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: "branch_larry_poison_negation",
    },
  },
];

export const NARRATIVE_SCENE_FIXTURES: readonly NarrativeScene[] = [
  {
    id: "scene_larry_day",
    kind: "scene",
    title: "Larry at Sea",
    order: 1,
    chapterId: "chapter_larry_story",
    assertionIds: ["nar_larry_boat", "nar_larry_fish", "nar_larry_dinner"],
    storyUnitIds: ["su_larry_day"],
    draftText: "Larry got on a boat. Larry caught a fish. Larry had dinner with friends.",
    provenance: systemDerivedProvenance,
    lifecycle: {
      ...authoredLifecycle,
      state: "active",
    },
    lineage: {
      originId: "scene_larry_day",
      parentIds: ["su_larry_day"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: "su_larry_day",
      supersededById: null,
      childIds: [],
      branchId: null,
    },
  },
  {
    id: "scene_larry_branch",
    kind: "scene",
    title: "Larry's Contradiction Branch",
    order: 2,
    chapterId: "chapter_larry_story",
    assertionIds: ["nar_larry_died", "nar_larry_survives", "nar_larry_poisoned", "nar_larry_not_poisoned"],
    storyUnitIds: ["su_larry_evening"],
    draftText: "Larry died of poison. Larry's wife poisoned him.",
    provenance: systemDerivedProvenance,
    lifecycle: {
      ...authoredLifecycle,
      state: "candidate",
    },
    lineage: {
      originId: "scene_larry_branch",
      parentIds: ["su_larry_evening"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: "su_larry_evening",
      supersededById: null,
      childIds: [],
      branchId: "branch_larry_contradiction",
    },
  },
];

export const NARRATIVE_CHAPTER_FIXTURES: readonly NarrativeChapter[] = [
  {
    id: "chapter_larry_story",
    kind: "chapter",
    title: "Larry Story",
    order: 1,
    sceneIds: ["scene_larry_day", "scene_larry_branch"],
    provenance: systemDerivedProvenance,
    lifecycle: authoredLifecycle,
    lineage: {
      originId: "chapter_larry_story",
      parentIds: ["scene_larry_day", "scene_larry_branch"],
      mergedFromIds: [],
      splitFromId: null,
      promotedFromId: null,
      supersededById: null,
      childIds: [],
      branchId: null,
    },
  },
];

export const NARRATIVE_OBJECT_FIXTURES: NarrativeObjectBundle = {
  assertions: NARRATIVE_ASSERTION_FIXTURES,
  storyUnits: NARRATIVE_STORY_UNIT_FIXTURES,
  gaps: NARRATIVE_GAP_FIXTURES,
  relationships: NARRATIVE_RELATIONSHIP_FIXTURES,
  scenes: NARRATIVE_SCENE_FIXTURES,
  chapters: NARRATIVE_CHAPTER_FIXTURES,
};

