name: Security Audit

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  pip-audit:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.lock
            requirements.dev.lock
            pyproject.toml

      - name: Install project (dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt .[dev]

      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Run pip-audit
        run: |
          pip-audit --strict -r requirements.lock -r requirements.dev.lock
